### ISSUE TITLE
Zoro: returns empty source and subtitle while fetching episode source

### ISSUE THREAD

**Issue by R4V3NSH4D0W** [consumet/consumet.ts#624] opened 2024-12-12 05:26 UTC
### Describe the bug

zoro fetchEpisodeSources return empty source and subtitle

### Steps to reproduce

1. pass an episode id to fetchEpisodeSource(episode_id)
2. returns empty source and subtitle

### Expected behavior

{
"sources": //videoSource,
"subtitles": [
//subtitles
]
}

### Actual behavior

{
"sources": [],
"subtitles": []
}

**Comment by Shikiiii** [comment] 2024-12-12 20:42
Duplicate of #623.

**Closed** 2024-12-21 04:45 UTC
Labels: bug
